### ISSUE TITLE
Crash Report with qmunitylib

### ISSUE THREAD

**Issue by AzurezEpic** [Qmunity/BluePower#274]
My game keeps crashing every time I have qmunitylib installed.Here's the crash report.
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 1/16/15 8:01 PM
Description: Initializing game

java.lang.NoClassDefFoundError: scala/collection/Seq
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.ILanguageAdapter$ScalaAdapter.getNewInstance(ILanguageAdapter.java:20)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:486)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: scala.collection.Seq
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 35 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:180)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.ILanguageAdapter$ScalaAdapter.getNewInstance(ILanguageAdapter.java:20)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:486)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 568758712 bytes (542 MB) / 1004011520 bytes (957 MB) up to 2077753344 bytes (1981 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1232 Minecraft Forge 10.13.2.1232 Optifine OptiFine_1.7.10_HD_U_B4 87 mods loaded, 87 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.85.1232} [Forge Mod Loader] (forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed
	Forge{10.13.2.1232} [Minecraft Forge] (forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed
	appliedenergistics2-core{rv2-beta-7} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed
	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed
	PlayerAPI{1.1} [Player API] (minecraft.jar) Unloaded->Constructed
	VeinMiner_coremod{0.21.0_build-35} [Core mod] (minecraft.jar) Unloaded->Constructed
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed
	debug{1.0} [debug] (Dense-Ores-Mod-1.7.10.jar) Unloaded->Constructed
	battlegear2{1.0.6.3} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.6.3.jar) Unloaded->Constructed
	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar) Unloaded->Constructed
	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed
	AetherCraft{1.4.3.24} [AetherCraft] (AetherCraft-1.7.10-1.4.3.24.jar) Unloaded->Constructed
	appliedenergistics2{rv2-beta-7} [Applied Energistics 2] (appliedenergistics2-rv2-beta-7.jar) Unloaded->Constructed
	bettersprinting{1.0} [Better Sprinting] (BetterSprinting.jar) Unloaded->Constructed
	bettervillages{0.4} [Better Villages Mod] (BetterVillages-0.4(1.7.10).jar) Unloaded->Constructed
	BiblioCraft{1.8.2} [BiblioCraft] (BiblioCraft-Mod-1.7.10.jar) Unloaded->Constructed
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed
	BiomesOPlenty{2.0.2} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.0.2.897-universal.jar) Unloaded->Constructed
	qmunitylib{1.0} [QmunityLib] (QmunityLib-1.7.10-0.1.69-universal.jar) Unloaded->Constructed
	bluepower{0.2.835} [Blue Power] (BluePower-1.7.10-0.2.835-universal.jar) Unloaded->Constructed
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-52.jar) Unloaded->Constructed
	BuildCraft|Core{6.2.6} [BuildCraft] (buildcraft-6.2.6.jar) Unloaded->Constructed
	BuildCraft|Transport{6.2.6} [BC Transport] (buildcraft-6.2.6.jar) Unloaded->Constructed
	BuildCraft|Silicon{6.2.6} [BC Silicon] (buildcraft-6.2.6.jar) Unloaded->Constructed
	BuildCraft|Builders{6.2.6} [BC Builders] (buildcraft-6.2.6.jar) Unloaded->Constructed
	BuildCraft|Energy{6.2.6} [BC Energy] (buildcraft-6.2.6.jar) Unloaded->Constructed
	BuildCraft|Factory{6.2.6} [BC Factory] (buildcraft-6.2.6.jar) Unloaded->Constructed
	chocolateQuest{0.0} [Chocolate Quest] (chocolateQuest-1.7.10-BETA2.jar) Unloaded->Constructed
	ComputerCraft{1.65} [ComputerCraft] (ComputerCraft1.65.jar) Unloaded->Constructed
	MineFactoryReloaded{1.7.10R2.8.0RC6} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	EnderIO{1.7.10-2.2.6.313_beta} [Ender IO] (EnderIO-1.7.10-2.2.6.313_beta.jar) Unloaded->Constructed
	EnderStorage{1.4.5.27} [EnderStorage] (EnderStorage-1.7.10-1.4.5.27-universal.jar) Unloaded->Constructed
	exnihilo{1.34} [Ex Nihilo] (Ex-Nihilo-1.34.jar) Unloaded->Constructed
	extvil{1.7.10-1.3} [Extended_Villages] (Extended-Villages-Mod-1.7.10.jar) Unloaded->Constructed
	ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC1-13.jar) Unloaded->Constructed
	ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B8-23.jar) Unloaded->Constructed
	TConstruct{1.7.10-1.7.1.build771} [Tinkers' Construct] (TConstruct-1.7.10-1.7.1c.jar) Unloaded->Constructed
	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed
	Baubles{1.0.1.8} [Baubles] (Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed
	ExtraUtilities{1.1.0k} [Extra Utilities] (extrautilities-1.1.0k.jar) Unloaded->Constructed
	iChunUtil{4.1.2} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) Unloaded->Constructed
	IC2{2.2.657-experimental} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.7.10.jar) Unloaded->Constructed
	InfernalMobs{1.5.4} [Infernal Mobs] (InfernalMobs-1.7.10.jar) Unloaded->Constructed
	IronChest{6.0.41.729} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) Unloaded->Constructed
	JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed
	magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (Magical-Crops-Mod-1.7.10.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC6} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC6} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC6} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC6} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC6} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC6} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC6} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC6} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC6} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC6} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC6} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC6} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC6} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC6} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	Thaumcraft{4.2.1.4} [Thaumcraft] (Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC6} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC6} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC6} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC6} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC6} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed
	miners{v3.1.0} [Miner's Heaven] (Miners-Heaven-Mod-1.7.10.jar) Unloaded->Constructed
	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) Unloaded->Constructed
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.7.10.jar) Unloaded->Constructed
	newdungeons{0.3} [New Dungeons] (New-Dungeons-Mod-1.7.10.jar) Unloaded->Constructed
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-246.jar) Unloaded->Constructed
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-475.jar) Unloaded->Constructed
	oreganic{R1.2} [Oreganics] (Oreganics-MC1.7.10 - R1.2.jar) Unloaded->Constructed
	PneumaticCraft{1.5.1-49} [PneumaticCraft] (PneumaticCraft-1.7.10-1.5.1-49-universal.jar) Unloaded->Constructed
	progressiveautomation{1.3.0} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.3.0.jar) Unloaded->Constructed
	rftools{2.01} [RFTools] (rftools-2.01.jar) Unloaded->Constructed
	roar{1.1} [R.O.A.R. The Root of All Automation. Really.] (roar-1.1.jar) Unloaded->Constructed
	VeinMiner{0.21.0} [Vein Miner] (VeinMiner-1.7.10_0.21.0.jar) Unloaded->Constructed
	VeinMinerModSupport{0.21.0} [Mod Support] (VeinMiner-1.7.10_0.21.0.jar) Unloaded->Constructed
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed
	denseores{1.0} [Dense Ores] (Dense-Ores-Mod-1.7.10.jar) Unloaded->Constructed
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded
	AE2 Version: beta rv2-beta-7 for Forge 10.13.2.1230
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 570M/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [§lDefault 3D§r             §lV1.9.6.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Quetzi** [comment]
This crash is not anything to do with us I think. We don't use scala. I'll leave it open for now though for the other devs to look at, I would check some of the other mods in your install.

**Comment by amadornes** [comment]
This has nothing to do with BluePower nor QmunityLib indeed

**Comment by AzurezEpic** [comment]
So is there anything I can so to prevent crashing while using
qmumitylib?Also, even after I uninstalled qmunitylib, my game was still
crashing, so I had to reinstall Minecraft, replace my saves, reinstall
forge and liteloader, all kinds of crap that took me 2 hours.Just sayin'...

**Comment by Quetzi** [comment]
It would continue to crash because, as we said, this crash has nothing to do with BluePower or Qmunitylib. I would look at the mods that actually use scala to find the problem (NEI, FMP, MPS etc)

**Comment by AzurezEpic** [comment]
Ah, well you may have to look through my mods for a long time, since I have
more than 60 mods.

**Comment by Quetzi** [comment]
I don't intend to do any such thing, not entirely sure why you would expect me to.
