### ISSUE TITLE
Crash when converting world over from an old version

### ISSUE THREAD

**Issue by MastaC729** [Qmunity/BluePower#297]
Forge Version: 10.13.2.1291

I get the following crash when I try to convert the world over from an old version of a couple months ago:

java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
        at com.bluepowermod.convert.WorldConverter.convertTile(WorldConverter.java:163) ~[WorldConverter.class:?]
        at com.bluepowermod.convert.WorldConverter.convertRegion(WorldConverter.java:143) ~[WorldConverter.class:?]
        at com.bluepowermod.convert.WorldConverter.convert(WorldConverter.java:74) ~[WorldConverter.class:?]
        at com.bluepowermod.convert.WorldConverter.convertIfNeeded(WorldConverter.java:60) ~[WorldConverter.class:?]
        at com.bluepowermod.convert.WorldConversionEventHandler.onWorldPreLoad(WorldConversionEventHandler.java:12) ~[WorldConversionEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_109_WorldConversionEventHandler_onWorldPreLoad_Load.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:230) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityClientPlayerMP
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_45]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_45]
        ... 12 more

Let me know if you need any additional information.

**Comment by Nhawks1717** [comment]
I'm having a similar crash when trying to load Blue Power onto a world previously without the mod. [here](http://pastebin.com/XUC91M2b) is the report.

**Comment by jasonsaffle13** [comment]
I fixed mine by grabbing the newest version of Qmunitylib!!

**Comment by Quetzi** [comment]
Yea, should be fixed with newest BP and QmunityLib
