### ISSUE TITLE
Build script is broken

### ISSUE THREAD

**Issue by SoniEx2** [Qmunity/BluePower#353]
More specifically you can't run the client while deving...

**Comment by K-4U** [comment]
Crashlog or gtfo

**Comment by SoniEx2** [comment]
No crash, it complains about Forge 10.3.3 thanks to CodeChickenCore (silent upgrades?)

**Comment by K-4U** [comment]
So, log or it didn't happen

**Comment by K-4U** [comment]
Already resolved trough IRC.

**Comment by SoniEx2** [comment]
If I manually change the Forge version to the Forge version it complains about:

```
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1168) ~[EntityRenderer.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1068) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:962) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:164) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
	at GradleStart.main(Unknown Source) [start/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:?]
Caused by: java.lang.NoSuchMethodError: codechicken.lib.gui.GuiDraw.drawMultilineTip(Lnet/minecraft/client/gui/FontRenderer;IILjava/util/List;)V
	at codechicken.nei.guihook.GuiContainerManager.renderToolTips(GuiContainerManager.java:414) ~[GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:181) ~[GuiContainer.class:?]
	at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:44) ~[InventoryEffectRenderer.class:?]
	at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:673) ~[GuiContainerCreative.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1137) ~[EntityRenderer.class:?]
	... 16 more
[15:15:52] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:displayCrashReport:388]: ---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 27/05/15 3:15 PM
Description: Rendering screen

java.lang.NoSuchMethodError: codechicken.lib.gui.GuiDraw.drawMultilineTip(Lnet/minecraft/client/gui/FontRenderer;IILjava/util/List;)V
	at codechicken.nei.guihook.GuiContainerManager.renderToolTips(GuiContainerManager.java:414)
	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:181)
	at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:44)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:673)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1137)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1068)
	at net.minecraft.client.Minecraft.run(Minecraft.java:962)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codechicken.nei.guihook.GuiContainerManager.renderToolTips(GuiContainerManager.java:414)
	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:181)
	at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:44)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:673)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (213, 119). Absolute: (427, 240)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Player682'/198, l='MpServer', x=723.29, y=5.62, z=-308.72]]
	Chunk stats: MultiplayerChunkCache: 612, 612
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (720,4,-311), Chunk: (at 0,0,9 in 45,-20; contains blocks 720,0,-320 to 735,255,-305), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Level time: 3157 game time, 3157 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 92 total; [EntityCow['Cow'/4, l='MpServer', x=651.16, y=4.00, z=-324.16], EntitySheep['Sheep'/5, l='MpServer', x=649.60, y=4.00, z=-324.71], EntitySheep['Sheep'/6, l='MpServer', x=648.41, y=4.00, z=-310.28], EntitySheep['Sheep'/7, l='MpServer', x=648.81, y=4.00, z=-318.25], EntityPig['Pig'/8, l='MpServer', x=650.41, y=4.00, z=-313.88], EntityChicken['Chicken'/129, l='MpServer', x=774.44, y=4.00, z=-317.41], EntityCow['Cow'/10, l='MpServer', x=652.22, y=4.00, z=-314.78], EntityCow['Cow'/11, l='MpServer', x=654.75, y=4.00, z=-312.41], EntitySheep['Sheep'/130, l='MpServer', x=771.81, y=4.00, z=-312.38], EntitySheep['Sheep'/12, l='MpServer', x=655.75, y=4.00, z=-318.72], EntitySheep['Sheep'/154, l='MpServer', x=802.06, y=4.00, z=-311.84], EntityCow['Cow'/25, l='MpServer', x=660.69, y=4.00, z=-316.63], EntityCow['Cow'/27, l='MpServer', x=666.69, y=4.00, z=-287.84], EntityHorse['Horse'/26, l='MpServer', x=663.25, y=4.00, z=-291.66], EntitySheep['Sheep'/29, l='MpServer', x=670.50, y=4.00, z=-288.88], EntityPig['Pig'/149, l='MpServer', x=803.69, y=4.00, z=-326.06], EntitySheep['Sheep'/28, l='MpServer', x=667.81, y=4.00, z=-288.75], EntityCow['Cow'/31, l='MpServer', x=665.88, y=4.00, z=-289.06], EntityHorse['Horse'/30, l='MpServer', x=664.80, y=4.00, z=-301.12], EntitySheep['Sheep'/34, l='MpServer', x=653.82, y=4.00, z=-279.15], EntityCow['Cow'/35, l='MpServer', x=666.49, y=4.00, z=-292.13], EntityPig['Pig'/32, l='MpServer', x=656.41, y=4.00, z=-290.78], EntitySheep['Sheep'/33, l='MpServer', x=668.25, y=4.00, z=-274.16], EntitySheep['Sheep'/38, l='MpServer', x=669.94, y=4.00, z=-286.38], EntitySheep['Sheep'/39, l='MpServer', x=670.34, y=4.00, z=-294.75], EntitySheep['Sheep'/36, l='MpServer', x=665.75, y=4.00, z=-286.03], EntityPig['Pig'/37, l='MpServer', x=664.50, y=4.00, z=-278.22], EntityChicken['Chicken'/42, l='MpServer', x=667.06, y=4.00, z=-280.38], EntitySheep['Sheep'/43, l='MpServer', x=663.38, y=4.00, z=-275.63], EntityChicken['Chicken'/40, l='MpServer', x=657.59, y=4.00, z=-276.53], EntityChicken['Chicken'/41, l='MpServer', x=669.16, y=4.00, z=-284.38], EntityChicken['Chicken'/46, l='MpServer', x=674.44, y=4.00, z=-268.56], EntityChicken['Chicken'/47, l='MpServer', x=668.50, y=4.00, z=-262.50], EntitySheep['Sheep'/44, l='MpServer', x=666.94, y=4.00, z=-278.38], EntityChicken['Chicken'/45, l='MpServer', x=662.59, y=4.00, z=-273.34], EntitySheep['Sheep'/51, l='MpServer', x=670.97, y=4.00, z=-269.53], EntityChicken['Chicken'/50, l='MpServer', x=670.78, y=4.00, z=-271.09], EntityChicken['Chicken'/49, l='MpServer', x=669.50, y=4.00, z=-271.50], EntityChicken['Chicken'/48, l='MpServer', x=666.72, y=4.00, z=-267.28], EntitySheep['Sheep'/53, l='MpServer', x=672.45, y=4.00, z=-248.75], EntityPig['Pig'/52, l='MpServer', x=658.44, y=4.00, z=-268.50], EntitySheep['Sheep'/59, l='MpServer', x=685.03, y=4.00, z=-338.50], EntityChicken['Chicken'/63, l='MpServer', x=673.63, y=4.00, z=-275.59], EntityChicken['Chicken'/62, l='MpServer', x=680.34, y=4.00, z=-279.56], EntitySheep['Sheep'/61, l='MpServer', x=674.03, y=4.00, z=-282.66], EntityPig['Pig'/60, l='MpServer', x=681.22, y=4.00, z=-326.88], EntitySheep['Sheep'/68, l='MpServer', x=678.03, y=4.00, z=-258.28], EntitySheep['Sheep'/69, l='MpServer', x=680.53, y=4.00, z=-260.53], EntitySheep['Sheep'/70, l='MpServer', x=669.05, y=4.00, z=-269.50], EntityClientPlayerMP['Player682'/198, l='MpServer', x=723.29, y=5.62, z=-308.72], EntityChicken['Chicken'/71, l='MpServer', x=678.72, y=4.00, z=-264.59], EntityPig['Pig'/64, l='MpServer', x=672.84, y=4.00, z=-279.59], EntitySheep['Sheep'/65, l='MpServer', x=686.88, y=4.00, z=-267.03], EntitySheep['Sheep'/66, l='MpServer', x=680.88, y=4.00, z=-263.06], EntitySheep['Sheep'/67, l='MpServer', x=679.19, y=4.00, z=-261.13], EntityCow['Cow'/76, l='MpServer', x=698.13, y=4.00, z=-341.94], EntityCow['Cow'/77, l='MpServer', x=690.59, y=4.00, z=-337.28], EntitySheep['Sheep'/78, l='MpServer', x=691.50, y=4.00, z=-332.66], EntitySheep['Sheep'/79, l='MpServer', x=694.75, y=4.00, z=-327.19], EntityChicken['Chicken'/72, l='MpServer', x=671.16, y=4.00, z=-265.09], EntityChicken['Chicken'/73, l='MpServer', x=682.34, y=4.00, z=-267.91], EntityChicken['Chicken'/74, l='MpServer', x=682.41, y=4.00, z=-267.38], EntitySheep['Sheep'/75, l='MpServer', x=680.84, y=4.00, z=-249.72], EntityChicken['Chicken'/85, l='MpServer', x=703.02, y=4.00, z=-270.09], EntitySheep['Sheep'/84, l='MpServer', x=690.69, y=4.00, z=-319.22], EntityPig['Pig'/81, l='MpServer', x=698.19, y=4.00, z=-331.56], EntityCow['Cow'/80, l='MpServer', x=696.63, y=4.00, z=-335.88], EntityPig['Pig'/83, l='MpServer', x=699.31, y=4.00, z=-334.47], EntityCow['Cow'/82, l='MpServer', x=696.69, y=4.00, z=-334.72], EntityChicken['Chicken'/95, l='MpServer', x=731.53, y=4.00, z=-369.56], EntityCow['Cow'/94, l='MpServer', x=721.16, y=4.00, z=-388.16], EntityChicken['Chicken'/102, l='MpServer', x=731.53, y=4.00, z=-367.59], EntityChicken['Chicken'/103, l='MpServer', x=721.27, y=4.00, z=-371.11], EntityChicken['Chicken'/100, l='MpServer', x=727.56, y=4.00, z=-372.47], EntityChicken['Chicken'/101, l='MpServer', x=734.47, y=4.00, z=-364.56], EntityChicken['Chicken'/98, l='MpServer', x=727.72, y=4.00, z=-371.59], EntityChicken['Chicken'/99, l='MpServer', x=731.44, y=4.00, z=-381.44], EntityCow['Cow'/96, l='MpServer', x=735.28, y=4.00, z=-371.78], EntityCow['Cow'/97, l='MpServer', x=733.50, y=4.00, z=-378.50], EntityChicken['Chicken'/110, l='MpServer', x=738.53, y=4.00, z=-320.56], EntitySheep['Sheep'/111, l='MpServer', x=742.81, y=4.00, z=-312.50], EntityChicken['Chicken'/108, l='MpServer', x=748.41, y=4.00, z=-368.44], EntityCow['Cow'/109, l='MpServer', x=742.94, y=4.00, z=-367.03], EntityChicken['Chicken'/104, l='MpServer', x=736.44, y=4.00, z=-290.63], EntityCow['Cow'/105, l='MpServer', x=721.97, y=4.00, z=-230.09], EntitySheep['Sheep'/119, l='MpServer', x=765.84, y=4.00, z=-303.72], EntitySheep['Sheep'/118, l='MpServer', x=767.81, y=4.00, z=-290.34], EntityChicken['Chicken'/117, l='MpServer', x=756.19, y=4.00, z=-299.66], EntitySheep['Sheep'/116, l='MpServer', x=758.78, y=4.00, z=-305.94], EntitySheep['Sheep'/115, l='MpServer', x=756.53, y=4.00, z=-306.88], EntityPig['Pig'/124, l='MpServer', x=775.50, y=4.00, z=-388.50], EntitySheep['Sheep'/120, l='MpServer', x=755.97, y=4.00, z=-303.09]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:415)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2567)
	at net.minecraft.client.Minecraft.run(Minecraft.java:983)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 4.0.3-1-ck
	Java Version: 1.7.0_79, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 675725464 bytes (644 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1408 11 mods loaded, 11 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.99.99} [Forge Mod Loader] (forgeSrc-1.7.10-10.13.3.1408-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.3.1408} [Minecraft Forge] (forgeSrc-1.7.10-10.13.3.1408-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-dev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.6.44} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	qmunitylib{1.0} [QmunityLib] (QmunityLib-0.1.109-deobf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bluepower{${version}} [Blue Power] (BluePower) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.0.311} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.311-dev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.0.311} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.311-dev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Waila{1.5.7} [Waila] (Waila-1.5.7a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.0.311} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.311-dev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GL info: ' Vendor: 'X.Org' Version: '3.0 Mesa 10.5.5' Renderer: 'Gallium 0.4 on AMD CAYMAN'
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Gallium 0.4 on AMD CAYMAN GL version 3.0 Mesa 10.5.5, X.Org
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
[15:15:52] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:displayCrashReport:398]: #@!@# Game crashed! Crash report saved to: #@!@# /home/soniex2/git/github/minecraft/mods/BluePower/eclipse/assets/./crash-reports/crash-2015-05-27_15.15.52-client.txt
[15:15:52] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[15:15:52] [Client thread/INFO] [FML]: Server terminated.
```

**Comment by MrKickkiller** [comment]
@SoniEx2: Problem has been found /solved by GirafiStudios
Cause: Outdated dependency of Waila.

Chicken-Bones/NotEnoughItems#212.

**Comment by SoniEx2** [comment]
Push fix to BP?

**Comment by MrKickkiller** [comment]
A. It is not really broken on BP's side. It's apparently Waila that still references and old method from CCLib or CCC
B. All BP devs are having no issues because of them not having done a new SetupDecompWorkspace in a while.
C. Already notified and asked Quetzi. He is aware that there is a problem at this moment. It will get fixed in a bit.
