### ISSUE TITLE
Unable to start server on Linux when X11 display is set but no X server is running

### ISSUE THREAD

**Issue by wrycu** [Qmunity/BluePower#412]
Not sure if this is a dupe of #380 or not (the pastebin has long disappeared), but running a brand-new download of FTB Horizons: Daybreaker dies with a stacktrace from BluePower: 

```
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.bluepowermod.part.PartInfo.create(PartInfo.java:73)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.bluepowermod.part.PartInfo.<init>(PartInfo.java:50)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.bluepowermod.part.PartManager.registerPart(PartManager.java:75)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.bluepowermod.part.PartManager.registerParts(PartManager.java:129)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.bluepowermod.BluePower.init(BluePower.java:98)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.lang.reflect.Method.invoke(Method.java:497)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.lang.reflect.Method.invoke(Method.java:497)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.lang.reflect.Method.invoke(Method.java:497)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.security.AccessController.doPrivileged(Native Method)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.lang.Class.forName0(Native Method)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.lang.Class.forName(Class.java:264)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at uk.co.qmunity.lib.texture.Layout.getLayout(Layout.java:86)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at uk.co.qmunity.lib.texture.Layout.getLayout(Layout.java:78)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.bluepowermod.part.gate.component.GateComponentTorch.onLayoutRefresh(GateComponentTorch.java:91)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.bluepowermod.part.gate.component.GateComponentTorch.<init>(GateComponentTorch.java:38)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.bluepowermod.part.gate.digital.GateAnd.initComponents(GateAnd.java:51)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.bluepowermod.part.gate.GateBase.<init>(GateBase.java:107)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.bluepowermod.part.gate.GateSimple.<init>(GateSimple.java:6)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.bluepowermod.part.gate.digital.GateSimpleDigital.<init>(GateSimpleDigital.java:8)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at com.bluepowermod.part.gate.digital.GateAnd.<init>(GateAnd.java:26)
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    ... 40 more
```

This can be worked around by clearing the DISPLAY environment variable, or by starting an X server.  Not sure why it's trying to connect to it given that the server was launched in nogui mode, though.

Server stack trace: http://pastebin.com/uFjDvnBn

**Comment by MoreThanHidden** [comment]
No longer an issue on modern versions.
