### ISSUE TITLE
Clash Bluepower

### ISSUE THREAD

**Issue by ttgk** [Qmunity/BluePower#454]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 16/08/04 17:42
Description: Initializing game

java.lang.NullPointerException: Initializing game
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
    at com.bluepowermod.util.ItemStackUtils.isItemFuzzyEqual(ItemStackUtils.java:41)
    at com.bluepowermod.recipe.AlloyFurnaceRegistry.generateRecyclingRecipes(AlloyFurnaceRegistry.java:242)
    at com.bluepowermod.BluePower.postInit(BluePower.java:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
    at com.bluepowermod.util.ItemStackUtils.isItemFuzzyEqual(ItemStackUtils.java:41)
    at com.bluepowermod.recipe.AlloyFurnaceRegistry.generateRecyclingRecipes(AlloyFurnaceRegistry.java:242)
    at com.bluepowermod.BluePower.postInit(BluePower.java:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 574283896 bytes (547 MB) / 1571766272 bytes (1498 MB) up to 4187619328 bytes (3993 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D3 59 mods loaded, 59 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJ   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJ   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJ   appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJ   CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) 
    UCHIJ   NotEnoughItems{1.0.3.74} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
    UCHIJ   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJ   net.minecraft.scalar.cutall.mod_CutAllSMP{2.5.0} [CutAllSMP](%5B1.7.10%5D%5Bforge1291%5Dmod_CutAllSMP_v2.5.0.zip) 
    UCHIJ   net.minecraft.scalar.mineall.mod_MineAllSMP{2.6.1} [MineAllSMP](%5B1.7.10%5D%5Bforge1291%5Dmod_MineAllSMP_v2.6.1.zip) 
    UCHIJ   net.minecraft.scalar.digall.mod_DigAllSMP{2.3.0} [DigAllSMP]([1.7.10][forge1291]mod_DigAllSMP_v2.3.0.zip) 
    UCHIJ   CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-1.7.103.1.2-325.jar) 
    UCHIJ   BuildCraft|Core{7.1.5} [BuildCraft](buildcraft-7.1.5.jar) 
    UCHIJ   BuildCraft|Transport{7.1.5} [BC Transport](buildcraft-7.1.5.jar) 
    UCHIJ   BuildCraft|Silicon{7.1.5} [BC Silicon](buildcraft-7.1.5.jar) 
    UCHIJ   BuildCraft|Factory{7.1.5} [BC Factory](buildcraft-7.1.5.jar) 
    UCHIJ   BuildCraft|Robotics{7.1.5} [BC Robotics](buildcraft-7.1.5.jar) 
    UCHIJ   IC2{2.2.681-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.681-experimental.jar) 
    UCHIJ   ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102 %281%29.jar) 
    UCHIJ   ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218 %281%29.jar) 
    UCHIJ   LogisticsPipes{0.9.3.126} [Logistics Pipes](logisticspipes-0.9.3.126.jar) 
    UCHIJ   additionalpipes{4.7.0} [Additional Pipes](additionalpipes-4.7.2.jar) 
    UCHIJ   appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHIJ   qmunitylib{1.0} [QmunityLib](QmunityLib-1.7.10-0.1.114-universal %283%29.jar) 
    UCHIE   bluepower{0.2.962} [Blue Power](BluePower-1.7.10-0.2.962-universal %283%29.jar) 
    UCHIJ   BuildCraft|Builders{7.1.5} [BC Builders](buildcraft-7.1.5.jar) 
    UCHIJ   BuildCraft|Energy{7.1.5} [BC Energy](buildcraft-7.1.5.jar) 
    UCHIJ   GVCEntity{1.7.x-srg-1} [GVCEntity](GVCGunsReversion1.7.x.5.0..1.zip) 
    UCHIJ   GVCGuns{1.7.x-srg-1} [GVCGuns](GVCGunsReversion1.7.x.5.0..1.zip) 
    UCHIJ   HandmadeGuns{1.7.x-srg-1} [HandmadeGuns](handmadeguns) 
    UCHIJ   IronChest{6.0.43.730} [Iron Chest](ironchest-1.7.10-6.0.43.730-universal.jar) 
    UCHIJ   mcheli{0.10.8} [MC Helicopter](mcheli) 
    UCHIJ   ForgeMultipart{1.1.2.331} [Forge Multipart](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCHIJ   Mekanism{8.1.9} [Mekanism](Mekanism-1.7.10-8.1.9.265.jar) 
    UCHIJ   MekanismGenerators{8.1.9} [MekanismGenerators](MekanismGenerators-1.7.10-8.1.9.265.jar) 
    UCHIJ   MekanismTools{8.1.9} [MekanismTools](MekanismTools-1.7.10-8.1.9.265.jar) 
    UCHIJ   MineFactoryReloaded{1.7.10R2.8.0RC8} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC8} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC8} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC8} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC8} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC8} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC8} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC8} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC8} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC8} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC8} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC8} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC8} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC8} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC8} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC8} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC8} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC8} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC8} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC8} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) 
    UCHIJ   SlimevoidLib{2.0.4.7} [Slimevoid Library](SlimevoidLibrary-2.0.4.7.jar) 
    UCHIJ   WirelessRedstoneCore{1.8.0.0} [Wireless Redstone](WirelessRedstoneCore-1.8.0.0.jar) 
    UCHIJ   McMultipart{1.1.2.331} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCHIJ   ForgeMicroblock{1.1.2.331} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.39' Renderer: 'GeForce GTX 960/PCIe/SSE2'
    CoFHCore: -[1.7.10]3.1.2-325
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    MineFactoryReloaded: -[1.7.10]2.8.0RC8-86
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.39, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: 日本語 (日本)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
OptiFine Version: OptiFine_1.7.10_HD_U_D3
Render Distance Chunks: 13
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
OpenGlVersion: 4.5.0 NVIDIA 368.39
OpenGlRenderer: GeForce GTX 960/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 4
```

**Comment by MoreThanHidden** [comment]
No longer relevant in current version.
