### ISSUE TITLE
lots of errors in logs

### ISSUE THREAD

**Issue by bloodyraoul** [Qmunity/BluePower#552]
### What were you doing when the issue happened? ###
When the game is loading, there are lots of errors in the client logs about blue power

### Full Log and Crashlog on pastebin/gist ###
https://pastebin.com/Bsa1yAaM
### Forge and Minecraft version ###
Version de Minecraft : 1.15.2
forge-31.1.63
### Bluepower version and build number ###
bluepower-1.15.2-0.4.188-alpha-universal.jar

**Comment by MoreThanHidden** [comment]
Sorry none of these errors are blue power, mostly seem to be evelon_deco

**Comment by bloodyraoul** [comment]
I thought first like you so I have contacted evelon mod author but he told me that because of this kind of error, it can be blue power parsing method :
**at com.bluepowermod.BluePower.onServerStarted(BluePower.java:127) [?:0.4.188-alpha]**
    at net.minecraftforge.eventbus.ASMEventHandler_35_BluePower_onServerStarted_FMLServerStartedEvent.invoke(.dynamic) [?:?]
    at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) [eventbus-2.1.0-service.jar:?]
    at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) [eventbus-2.1.0-service.jar:?]
    at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:95) [?:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:614) [?:?]

**Comment by MoreThanHidden** [comment]
Yeah I saw that, is just because I'm triggering a reload to pull in the dynamic alloy smelter recipes, I'll change the way they are generated so it stops appearing in the stack-trace.
